---
- name: install graphite-web packages
  sudo: yes
  apt: name=graphite-web state=present

- name: configure application secret
  sudo: yes
  lineinfile:
    dest=/etc/graphite/local_settings.py
    state=present
    regexp="^SECRET_KEY"
    insertafter="^#SECRET_KEY"
    line="SECRET_KEY = 'itsaseekret'"

- name: sync database
  sudo: yes
  command: graphite-manage syncdb

- name: correct sqlite db file permissions
  sudo: yes
  file:
    path=/var/lib/graphite/graphite.db
    state=touch
    owner=_graphite
    group=_graphite
    mode=0644

- file:
    path=/var/log/nginx/graphite.vbox
    state=directory
    owner=www-data
    group=www-data
    mode=0600
  sudo: yes

- name: configure nginx site
  sudo: yes
  template:
    src=etc/nginx/sites-available/graphite
    dest=/etc/nginx/sites-available/graphite
    owner=root
    group=root
    mode=0644

- name: configure uwsgi app
  sudo: yes
  template:
    src=etc/uwsgi/apps-available/graphite.ini
    dest=/etc/uwsgi/apps-available/graphite.ini
    owner=root
    group=root
    mode=0644

- name: enable uwsgi app
  sudo: yes
  file:
    src=/etc/uwsgi/apps-available/graphite.ini
    dest=/etc/uwsgi/apps-enabled/graphite.ini
    owner=root
    group=root
    state=link
  notify:
    - restart uwsgi

- name: enable nginx site
  sudo: yes
  file:
    src=/etc/nginx/sites-available/graphite
    dest=/etc/nginx/sites-enabled/graphite
    owner=root
    group=root
    state=link
  notify:
    - restart nginx
